### ISSUE TITLE
Day Laborer Page - Page TITLE is Wrong

### ISSUE THREAD

**Issue by jfc3-dol** [presidential-innovation-fellows/worker-dol-gov#16]
While testing using the DHS Trusted Tester process, I noticed the page TITLE was "Worker.gov | Daylaborer Rights" should the words "day" and "Laborer" be split along with in front of the website name.Doing this will help with SEO. My suggested TITLE for the page should be as follows:

Day Laborer Rights - Worker.gov

All other pages should follow a similar TITLE naming process which would consist of what the page is about and then a dash and then Worker.gov. A few examples would be:

- Day Laborer - I didn't get paid for work performed - worker.gov
- My wage rights - You have the right to be paid - worker.gov

**Comment by adamsfallen** [comment]
Fixed - f373532a21f3832be5913ff907a3ce864138aa63
