### ISSUE TITLE
Hours Worked Violation Page - Duplicate Links

### ISSUE THREAD

**Issue by jfc3-dol** [presidential-innovation-fellows/worker-dol-gov#18]
While testing using the DHS Trusted Tester process, I noticed there seems to be another link behind the "File a Claim" button pointing to the same page.

**Comment by adamsfallen** [comment]
@jfc3-dol can you be more specific about where exactly you're finding the other link?

Is it the button on the violation page (http://worker.gov/profiles/daylaborer/hours-worked-violation.html) or the claim page (http://worker.gov/actions/whd-claim.html)?

And either way, where exactly do you see the duplicate link (and what do you mean by duplicate)?

**Comment by jfc3-dol** [comment]
Here is what I see when tabbing in three screenshots. I started at the "My wage Rights" link. See screenshot below:

![worker dot gov - tab from my wages rights](https://cloud.githubusercontent.com/assets/10423487/19745617/5ad632fa-9ba0-11e6-9f09-bccd1d6e0cf0.png)

Then I tabbed to the hidden link (see blue highlight under button) behind the "File a Claim" button. See screenshot below:

![worker dot gov - tab to blue highlighted link under file a claim button](https://cloud.githubusercontent.com/assets/10423487/19745647/7d193948-9ba0-11e6-817b-24639bf364ac.png)

Then after tabbing again I get to the "File a Claim" button. See screenshot below:

![worker dot gov - tab to claim button with blue highlight](https://cloud.githubusercontent.com/assets/10423487/19745665/9c050134-9ba0-11e6-88ec-f30b59bccad2.png)

Hope these screenshots and information is helpful. If you have any other questions on my other issues feel free to ask.

**Comment by jfc3-dol** [comment]
The page I was talking about was:

http://worker.gov/profiles/daylaborer/hours-worked-violation.html

**Comment by adamsfallen** [comment]
Okay I follow the issue - buttons were being wrapped in anchor tags creating two "tabbable" elements. Refactored and updated - 8119162e1333270ee28593ca2df2c1f06c024888

**Comment by jfc3-dol** [comment]
My guess is looking at these code updates that they should fix the issue for this page and others.
