### ISSUE TITLE
Home Page - "All Rights" Missing Visible Focus when Tabbing with Keyboard

### ISSUE THREAD

**Issue by jfc3-dol** [presidential-innovation-fellows/worker-dol-gov#2]
While testing using DHS Trusted Tester process, I found that the links that go to the "All Rights" page (all.html) are not visible when tabbing. It's difficult unless a person is looking directly at the "Learn My Rights" button to see if they are focused on or not when tabbing. Along with there seems to be another "All Rights" link behind or under the button.

Section 508 - 21(a)
WCAG 2.0 - 1.1 Keyboard Access

**Comment by adamsfallen** [comment]
The issue of the "Learn My Rights" button being less visible than a normal button should be resolved when we refactored the buttons 8119162e1333270ee28593ca2df2c1f06c024888

**Comment by jfc3-dol** [comment]
That works for me.
