### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by konklone** [presidential-innovation-fellows/worker-dol-gov#20]
It appears that worker.gov is intended for employees to use to look up their rights in a potentially hostile work environment. 

Since worker.gov doesn't support HTTPS (much less enforce it, or use HSTS), if an employee visits worker.gov while on their corporate network, their employer will see each specific page (e.g. `/profiles/all/whistleblower-retaliation.html`) that the worker visits. This could put the employee at greater risk of unwelcome oversight or retaliation. By default, [HTTPS will obscure this information from the network.](https://https.cio.gov/faq/#what-information-does-https-protect%3f) While some employers may use enterprise traffic inspection on their networks to observe even HTTPS traffic on work devices, this is not a universal practice. (And I have never personally worked for an employer that does this.)

HTTPS was a [federal requirement for all new websites as of June 2015](https://https.cio.gov/#guidelines). But more importantly, it's a necessary security and privacy baseline for all websites and for all visitors. Worker.gov should not have launched without HTTPS, and I hope the team will promptly prioritize adding and enforcing HTTPS and [HSTS](https://https.cio.gov/hsts/).

**Comment by MikePulsiferDOL** [comment]
Thank you for catching this.  We are working on resolving this.

**Comment by MikePulsiferDOL** [comment]
This has been implemented.

**Comment by konklone** [comment]
Unfortunately, this isn't fixed yet - when I visit http://worker.gov, I remain there and don't get redirected to https://worker.gov. This needs a server-side redirect.

In addition, there's no HSTS header (for increased client security and as [required by M-15-13](https://https.cio.gov/#guidelines)). It looks like the server is Microsoft IIS 8.5. We have some Microsoft IIS specific instructions for adding an HSTS header here:

https://https.cio.gov/hsts/#configuration-for-common-web-servers
